name: Deploy Node.js app

on:
  push:
    branches:
      - master  # Trigger deployment on push to main branch

jobs:
  deploy-to-face:
    name: Deploy to FACE
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            cd /root/projects/hamster-kombat-auto
            bash deploy.sh