name: Deploy Node.js app

on:
  push:
    branches:
      - master  # Trigger deployment on push to main branch

jobs:
  deploy-to-face:
    name: Deploy to FACE
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /root/projects/hamster-kombat-auto
            bash deploy.sh